# Generated by Django 5.1.1 on 2024-10-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rectangle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("length", models.IntegerField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
